name:                realworld
version:             0.1.0.0
github:              "githubuser/realworld"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/realworld#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- hasql
- hasql-th
- lucid
- lucid-htmx
- lucid-hyperscript
- servant
- servant-auth
- servant-auth-server
- servant-htmx
- servant-lucid
- servant-server
- text
- time
- warp

library:
  source-dirs: src

executables:
  realworld-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - realworld

tests:
  realworld-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - realworld
